### ISSUE TITLE
Lógica de negocio - Paciente quiere ser atendido acorde al riesgo que corre su salud

### ISSUE THREAD

**Issue by RubenDelgadoPareja** [RubenDelgadoPareja/TFG-Triaje-Inteligente-Consulta-Medica#112]
Para un paciente es un problema tener que esperar durante horas para ser atendido en urgencias sin tener en cuenta el riesgo de su salud. En situaciones dónde la carga de pacientes es muy alta debería de tenerse en cuenta el riesgo de los pacientes, además de automatizar la criba de la entrada a consulta usando la ayuda de un sistema informático.

Para esta issue vamos a centrarnos en el tiempo que tarda el sistema en gestionar el orden de los pacientes dependiendo de su prioridad, esto implica necesitar un valor preciso (numérico) para evaluar en que posición colocarlo. Teniendo en cuenta que la prioridad máxima es 0 y la mínima es 100 , vamos a introducir una carga de 50 pacientes con prioridades diversas con la tendencia de que pocos pacientes tengan prioridad alta y la mayoría tengan prioridades bajas. Además se tendrá en cuenta el tiempo que tarda el sistema en introducir y recolocar nuevos pacientes en la cola. Para minimizar el tiempo que tarda la cola en priorizar y reordenar debemos de hacer una pequeña investigación sobre qué algoritmos son los más rápidos, en la memoria debemos dejar reflejados la toma de decisiones y explicar de cuánto es la complejidad del algoritmo

Este problema forma parte de la HU #19 y ayuda a completarla

**Comment by JJ** [comment]
Como te he dicho ya, no puedes plantear la solución a un problema como un issue, porque no estás realmente analizando el problema, sino planteando una tarea que puede o no resolver el problema. Reformula el issue de forma que expliques todos los aspectos del problema y dé lugar a algo que puedas testear.

**Comment by RubenDelgadoPareja** [comment]
> Como te he dicho ya, no puedes plantear la solución a un problema como un issue, porque no estás realmente analizando el problema, sino planteando una tarea que puede o no resolver el problema. Reformula el issue de forma que expliques todos los aspectos del problema y dé lugar a algo que puedas testear.

Tengo una issue para la configuración de la herramienta de testing , debería de terminar esa issue antes no? es la #89

**Comment by JJ** [comment]
Sería conveniente que describieras qué sería para los clientes el problema resuelto. ¿Qué considerarían los pacientes una consulta bien atendida? ¿Qué sería para las enfermeras?

**Comment by JJ** [comment]
> La lógica de negocio necesita una cola para almacenar temporalmente y priorizar los pacientes que vayan llegando a urgencias. Por la manera que hemos planificado las diferentes issues, en esta vamos a centrarnos en la cola con prioridad.
> 

Sigues diciendo cuál es la solución, sin expresar claramente cuál es el problema.

> Para el cliente el problema se resolvería cuando el sistema informático sea capaz de simular la cola de espera pero teniendo en cuenta el riesgo del cliente y posicionándolo en el lugar que exigen sus necesidades médicas.

El cliente no sabe lo que es una cola de espera. No puedes formular el problema mencionando la solución que ya has decidido de antemano.

Los issues son descripciones de alto nivel que se convertirán más adelante en tests, que serán capaces de dilucidar si el código añade valor al cliente (soluciona el problema) o no. Entender esto es fundamental en ingeniería del software, donde se trata de solucionar problemas, no de escribir código.

Lo que tendría que explicarse en este issue es ¿cómo sabe el paciente que lo están tratando con la prioridad adecuada? ¿Cómo sabe la persona en triage en enfermería que está procediéndose con la prioridad correcta?

Por otro lado, la descripción del problema tiene también que servir para modelizar la carga. ¿Las pruebas, se hacen con 10 pacientes de mucha prioridad y 1 de baja? ¿5 de cada? ¿Quién asigna las prioridades también? ¿En función de qué?
