### ISSUE TITLE
Servicio de gestión de pacientes

### ISSUE THREAD

**Issue by RubenDelgadoPareja** [RubenDelgadoPareja/TFG-Triaje-Inteligente-Consulta-Medica#125]
Como dice la HU #19 , necesitamos de un servicio para poder recoger los datos del paciente que asiste a urgencias y transformarlos en el dominio del paciente. En el caso que decidamos guardar estos datos de forma persistente se abrirá otra issue para hacerlo.

**Comment by JJ** [comment]
¿Por qué haría falta guardarlo específicamente de forma persistente? ¿No hará falta simplemente guardarlo? ¿Y de qué forma habrá que guardarlo para que se pueda acceder a él?

**Comment by JJ** [comment]
Es que los issues no pueden ser tareas, tienen que ser problemas. Si pones una tarea y resulta que no resuelve nada, acabas quitándola y perdiendo el trabajo hecho. Si planteas claramente el problema en el marco y contexto adecuado, acabas entendiendo mejor el problema y eventualmente haciendo una solución adecuada al mismo.
